print("Welcome to Joy conference!\nPlease provide your details.")
Event_guest = input("Enter full name: ")
Event_guest = set()
Event_guest2 = input("Enter full name: ")
Event_guest.add(Event_guest2)
Event_guest3 = input("Enter full name: ")
Event_guest.add(Event_guest3)
Event_guest4 = input("Enter full name: ") 
Event_guest.add(Event_guest4)
print(sorted(Event_guest))